routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\GameController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\QuestionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['admin', 'auth']], function () {
    Route::get('admin', [DashboardController::class, 'index'])->name('dashboard');
    Route::prefix('admin')->group(function () {
        Route::resource('question', QuestionController::class);
    });
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/game', [GameController::class, 'index'])->name('play');
    Route::get('/create-game', [GameController::class, 'createGame'])->name('create-game');
    Route::get('/game/{game}', [GameController::class, 'getQuestion'])->name('game');
    Route::post('/game/answer', [GameController::class, 'answer'])->name('answer');
    Route::get('/top-players', [GameController::class, 'getTopPlayers'])->name('top-players');
});

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @property $theme string
 * @property $question string
 * @property $point string
 */
class Question extends Model
{
    use HasFactory;

    protected $fillable = [
        'theme',
        'question',
        'point'
    ];

    /**
     * Get all answers for each question
     *
     * @return HasMany
     */
    public function answers(): HasMany
    {
        return $this->hasMany(Answer::class);
    }
}

app/Http/Controllers/Admin/QuestionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\QuestionRequest;
use App\Models\Question;
use App\Repository\Interfaces\QuestionRepositoryInterface;
use App\Repository\QuestionRepository;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;

class QuestionController extends Controller
{
    /**
     * @var QuestionRepository
     */
    private $questionRepository;

    /**
     * @param QuestionRepository $questionRepository
     */
    public function __construct(QuestionRepositoryInterface $questionRepository)
    {
        $this->questionRepository = $questionRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $questions = $this->questionRepository->findAll();

        return view('admin.questions.index', compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('admin.questions.create');
    }

    /**
     * Store resource in storage.
     *
     * @param QuestionRequest $request
     * @return RedirectResponse
     */
    public function store(QuestionRequest $request): RedirectResponse
    {
        $data = $request->validated();

        /** @var Question $question */
        $question = $this->questionRepository->create($data);

        $question->answers()->createMany($data['answers']);

        $question->theme = Arr::get($data, 'theme');
        $question->question = Arr::get($data, 'question');
        $question->point = Arr::get($data, 'point');
        $question->save();

        return redirect()->route('question.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Question $question
     * @return Application|Factory|View
     */
    public function edit(Question $question)
    {
        return view('admin.questions.edit', ['questionAnswers' => $question]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param QuestionRequest $request
     * @param int $id
     * @return RedirectResponse
     */
    public function update(QuestionRequest $request, int $id): RedirectResponse
    {
        $data = $request->validated();

        /** @var Question $question */
        $question = $this->questionRepository->find($id);
        $question->answers()->delete();
        $question->answers()->createMany($data['answers']);

        $question->theme = Arr::get($data, 'theme', $question->theme);
        $question->question = Arr::get($data, 'question', $question->question);
        $question->point = Arr::get($data, 'point', $question->point);
        $question->save();

        return redirect()
            ->route('question.index')
            ->with('success', 'Question successfully updated!');
    }
}

resources/views/admin/questions/create.blade.php
@extends('layouts.admin')
@section('content')
    <h1 class="text-center">Create Question</h1>
    <div class="container">
        <div class="m-auto">
            <form action="{{ route('question.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <div class="col-12">
                        <label for="question-theme">Question theme</label>
                        <input type="text" name="theme" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-12">
                        <label for="question">Question</label>
                        <textarea class="form-control" name="question" id="question" rows="6"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-4">
                        <label for="point">Question point</label>
                        <input type="number" name="point" min="5" max="20" class="form-control" id="point" aria-describedby="emailHelp">
                        <small id="emailHelp" class="form-text text-muted">Write question point!</small>
                    </div>
                </div>
                <div id="main-answer">
                    <div class="answer-block" style="background-color: #f5f1f1; border-radius: 10px; margin-top: 10px">
                        <div class="form-group">
                            <div class="col-12">
                                <label for="point">Answer</label>
                                <input type="text" data-answer="1" name="answers[1][answer]" class="form-control answerInput">
                            </div>
                        </div>
                        <div class="form-check">
                            <div class="col-12">
                                <input type="checkbox" name="answers[1][accuracy]" value="1" class="form-check-input accuracy">
                                <label class="form-check-label" for="accuracy">Right or wrong!</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="answers" style="margin-top: 10px"></div>
                <div class="actions" style="margin-top: 10px">
                    <button class="btn btn-primary add-answer">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                        </svg>
                    </button>
                    <button class="btn btn-danger delete-answer">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-minus" viewBox="0 0 16 16">
                            <path d="M5.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H6a.5.5 0 0 1-.5-.5z"/>
                            <path d="M4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4zm0 1h8a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1z"/>
                        </svg>
                    </button>
                </div>
                <div style="margin-top: 20px">
                    <div class="col-1 float-right">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

@endsection

@section('scripts')
    <script>
        $(document).ready(function () {
            $('.add-answer').click(function (e) {
                e.preventDefault()
                console.log($('.answer-block'));
                let incrementNumber = $('.answer-block').length + 1

                let cloneElement = $('#main-answer .answer-block').clone()

                let accuracy = cloneElement.find('.accuracy');
                accuracy.prop('checked', false)
                accuracy.attr('name', 'answers['+incrementNumber+'][accuracy]')

                let answerInput = cloneElement.find('.answerInput');
                answerInput.val('').end().appendTo('#answers')
                answerInput.attr('name', 'answers['+incrementNumber+'][answer]')
            })

            $('.delete-answer').click(function (e) {
                e.preventDefault()
                $('#answers .answer-block').last().remove()
            })
        })
    </script>

@endsection

resources/views/admin/questions/edit.blade.php
@extends('layouts.admin')
@section('content')
    <h1 class="text-center">Edit Question</h1>
    <div class="container">
        <div class="m-auto">
            <form action="{{ route('question.update', ['question' => $questionAnswers->id]) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <div class="col-12">
                                <label for="question-theme">Question theme</label>
                                <input type="text" name="theme" class="form-control" value="{{ $questionAnswers->theme }}">
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <div class="col-12">
                                <label for="point">Question point</label>
                                <input type="number" value="{{ $questionAnswers->point }}" name="point" min="5" max="20" class="form-control" id="point" aria-describedby="emailHelp">
                                <small id="emailHelp" class="form-text text-muted">Write question point!</small>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-12">
                        <label for="question">Question</label>
                        <textarea class="form-control" name="question" id="question" rows="6">{{ $questionAnswers->question }}</textarea>
                    </div>
                </div>
                <div id="main-answer">
                    @foreach($questionAnswers->answers as $key => $answer)
                    <div class="answer-block" style="background-color: #f5f1f1; border-radius: 10px; margin-top: 10px">
                        <div class="form-group">
                            <div class="col-12">
                                <label for="point">Answer</label>
                                <input type="text" value="{{ $answer->answer }}" name="answers[{{ $key + 1 }}][answer]" class="form-control answerInput">
                            </div>
                        </div>
                        <div class="form-check">
                            <div class="col-12">
                                <input type="checkbox" name="answers[{{ $key + 1 }}][accuracy]" value="1" {{ $answer->accuracy ? 'checked' : '' }} class="form-check-input accuracy">
                                <label class="form-check-label" for="accuracy">Right or wrong!</label>
                            </div>
                        </div>
                    </div>
                    @endforeach
                </div>
                <div id="answers" style="margin-top: 10px"></div>
                <div class="actions" style="margin-top: 10px">
                    <button class="btn btn-primary add-answer">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                        </svg>
                    </button>
                    <button class="btn btn-danger delete-answer">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-minus" viewBox="0 0 16 16">
                            <path d="M5.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H6a.5.5 0 0 1-.5-.5z"/>
                            <path d="M4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4zm0 1h8a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1z"/>
                        </svg>
                    </button>
                </div>
                <div style="margin-top: 20px">
                    <div class="col-1 float-right">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

@endsection

@section('scripts')
    <script>
        $(document).ready(function () {
            $('.add-answer').click(function (e) {
                e.preventDefault()
                console.log($('.answer-block'));
                let incrementNumber = $('.answer-block').length + 1

                let cloneElement = $('#main-answer .answer-block').first().clone()

                let accuracy = cloneElement.find('.accuracy');
                accuracy.prop('checked', false)
                accuracy.attr('name', 'answers['+incrementNumber+'][accuracy]')

                let answerInput = cloneElement.find('.answerInput');
                answerInput.val('').end().appendTo('#answers')
                answerInput.attr('name', 'answers['+incrementNumber+'][answer]')
            })

            $('.delete-answer').click(function (e) {
                e.preventDefault()
                if ($('.answer-block').length > 1) {
                    $('#main-answer .answer-block').last().remove()
                }
            })
        })
    </script>

@endsection

resources/views/admin/questions/index.blade.php
@extends('layouts.admin')

@section('content')
    <h1 class="text-center">Questions</h1>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                <div class="col-9"></div>
                <div class="col-3">
                    <a href="{{ route('question.create') }}" class="btn btn-primary">
                        Add Question
                    </a>
                </div>
            </div>
            <br>
            <div class="row">
                @forelse($questions as $question)
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h5 class="card-title">{{ $question->theme }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">Question point: {{ $question->point }}</h6>
                            <p class="card-text">{{ $question->question }}</p>
                            <a href="{{ route('question.edit', ['question' => $question->id]) }}" class="card-link">Edit</a>
                        </div>
                    </div>
                </div>
                @empty
                    <div class="alert alert-info m-auto" role="alert">
                        You don't have a questions in database !!!
                    </div>
                @endforelse
            </div>
        </div>

    </div>
@endsection